apiVersion: v1
kind: Service
metadata:
  name: trading-app
  namespace: keda-demo
  labels:
    app: trading-app
spec:
  selector:
    app: trading-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
