apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trading-app-monitor
  namespace: keda-demo
spec:
  selector:
    matchLabels:
      app: trading-app
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
