apiVersion: v1
kind: Service
metadata:
  name: prom-app
  namespace: keda-demo
  labels:
    app: prom-app
spec:
  selector:
    app: prom-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
