apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: keda-demo
type: Opaque
stringData:
  POSTGRES_USER: kedauser
  POSTGRES_PASSWORD: kedapass
  POSTGRES_DB: kedadb
  CONNECTION_STRING: "postgresql://kedauser:kedapass@postgres.keda-demo.svc:5432/kedadb?sslmode=disable"
