apiVersion: v1
kind: Service
metadata:
  name: kafka-app
  namespace: keda-demo
  labels:
    app: kafka-app
spec:
  selector:
    app: kafka-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kafka-app
  namespace: keda-demo
spec:
  to:
    kind: Service
    name: kafka-app
  port:
    targetPort: http
