apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaler
  namespace: keda-demo
  annotations:
    autoscaling.keda.sh/paused: "false"
spec:
  scaleTargetRef:
    name: kafka-consumer
  pollingInterval: 10
  cooldownPeriod: 15
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: lightwell-kafka-bootstrap.lightwell-infra.svc:9092
        consumerGroup: keda-demo-consumer-group
        topic: keda-demo-orders
        lagThreshold: "50"
        offsetResetPolicy: earliest
